# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feat/*

# YAML file in the main branch
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

jobs:
- job: 'ParallelTesting'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    parallel: 1
  displayName: Run ReportPortal tests

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 6.8.0'
    inputs:
      versionSpec: 6.8.0
      checkLatest: true

  - task: DockerCompose@0
    inputs:
      dockerComposeFile: '**/docker-compose.yml'
      action: Run a Docker Compose command
      dockerComposeCommand: 'up -d --force-recreate'
      detached: false
      projectName: 'reportportal'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--no-build'
  - task: CopyFiles@2
    inputs:
      Contents: '**/logs/**, **/screenshots/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop