# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feat/*

# YAML file in the main branch
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

jobs:
- job: 'ParallelTesting'
  pool:
    vmImage: 'windows-2019'
  container: mcr.microsoft.com/windows/servercore:ltsc2019
  strategy:
    parallel: 1
  displayName: Run tests in parallel

  steps:
  - powershell: |
      # Install Docker (if not already installed)
      if (-Not (Test-Path 'C:\Program Files\Docker\Docker\Docker Desktop.exe')) {
          Invoke-WebRequest -Uri https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe -OutFile docker-installer.exe
          Start-Process -Wait -FilePath .\docker-installer.exe
      }
      Start-Service Docker
      docker compose -f docker-compose.yml -p reportportal up -d --force-recreate

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--no-build'
  - task: CopyFiles@2
    inputs:
      Contents: '**/logs/**, **/screenshots/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop
